[phases.setup]
nixPkgs = ["chromium", "nss", "atk", "cups", "pango", "xorg.libX11", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext", "xorg.libXfixes", "xorg.libXrandr", "glib", "gtk3", "libdrm", "mesa"]

[start]
cmd = "node server.js"
